import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "Docs",
      items: [
        "docs/intro",
        "docs/resolvers",
        "docs/mutations",
        "docs/inputs",
        "docs/error-messaging",
        "docs/case-conversion",
        "docs/fragments",
        "docs/scalars",
        "docs/enums",
        "docs/unions",
        "docs/interfaces",
        "docs/subscriptions",
        "docs/dataloaders",
        "docs/file-uploads",
        "docs/documenting-schema",
        "docs/modularization",
        "docs/bindables",
        "docs/schema-directives",
        "docs/local-development",
        "docs/logging",
        "docs/explorers",
        "docs/apollo-federation",
      ],
    },
    {
      type: "category",
      label: "Monitoring",
      items: ["monitoring/open-telemetry", "monitoring/open-tracing", "monitoring/apollo-tracing"],
    },
    {
      type: "category",
      label: "Security",
      items: [
        "security/security-overview",
        "security/hiding-field-suggestions",
        "security/disabling-stack-traces",
        "security/continuous-security-testing",
      ],
    },
    {
      type: "category",
      label: "Servers",
      items: ["servers/asgi", "servers/wsgi", "servers/aws-lambda"],
    },
    {
      type: "category",
      label: "Integrations",
      items: [
        "integrations/django-integration",
        "integrations/fastapi-integration",
        "integrations/flask-integration",
        "integrations/starlette-integration",
        "integrations/other-integrations",
      ],
    },
    {
      type: "category",
      label: "Extensions",
      items: ["extensions/extensions", "extensions/middleware", "extensions/query-validators", "extensions/query-stack"],
    },
    {
      type: "category",
      label: "Contrib",
      items: ["contrib/graphql-relay"],
    },
    {
      type: "category",
      label: "API reference",
      items: [
        "api-reference/api-reference",
        "api-reference/asgi-reference",
        "api-reference/asgi-handlers-reference",
        "api-reference/constants-reference",
        "api-reference/exceptions-reference",
        "api-reference/types-reference",
        "api-reference/wsgi-reference",
      ],
    },
    {
      type: "category",
      label: "Other",
      items: ["other/logo"],
    },
  ],
};

export default sidebars;
