import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "Docs",
      items: [
        "intro",
        "resolvers",
        "mutations",
        "inputs",
        "error-messaging",
        "case-conversion",
        "fragments",
        "scalars",
        "enums",
        "unions",
        "interfaces",
        "subscriptions",
        "dataloaders",
        "file-uploads",
        "documenting-schema",
        "modularization",
        "bindables",
        "schema-directives",
        "local-development",
        "logging",
        "explorers",
        "apollo-federation",
      ],
    },
    {
      type: "category",
      label: "Monitoring",
      items: ["open-telemetry", "open-tracing", "apollo-tracing"],
    },
    {
      type: "category",
      label: "Security",
      items: [
        "security-overview",
        "hiding-field-suggestions",
        "disabling-stack-traces",
        "continuous-security-testing",
      ],
    },
    {
      type: "category",
      label: "Servers",
      items: ["asgi", "wsgi", "aws-lambda"],
    },
    {
      type: "category",
      label: "Integrations",
      items: [
        "django-integration",
        "fastapi-integration",
        "flask-integration",
        "starlette-integration",
        "other-integrations",
      ],
    },
    {
      type: "category",
      label: "Extensions",
      items: ["extensions", "middleware", "query-validators", "query-stack"],
    },
    {
      type: "category",
      label: "Contrib",
      items: ["graphql-relay"],
    },
    {
      type: "category",
      label: "API reference",
      items: [
        "api-reference",
        "asgi-reference",
        "asgi-handlers-reference",
        "constants-reference",
        "exceptions-reference",
        "types-reference",
        "wsgi-reference",
      ],
    },
    {
      type: "category",
      label: "Other",
      items: ["logo"],
    },
  ],
};

export default sidebars;
